### ISSUE TITLE
Doesn't work in ie11

### ISSUE THREAD

**Issue by TrevorMartz** [Zenoo/react-append-head#6]
**Describe the bug**
When using `<AppendHead>` in any capacity the react app crashes in ie11 with the error `Object doesn't support property or method 'entries'`

**To Reproduce**
1. try to render any component with `<AppenHead>` in it and watch it crash.

**Expected behavior**
Should load in ie11

**Screenshots**
![image](https://user-images.githubusercontent.com/9042126/77004777-4c1e9300-6925-11ea-913a-a3374b7c6741.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser ie11
 - Version 1.0.10

**Comment by Zenoo** [comment]
Thanks for the report @TrevorMartz, I didn't test it in IE.
I will get around to it ASAP.

**Comment by TrevorMartz** [comment]
I was able to workaround the issue using this SO post as reference. Should be useful for your fix. https://stackoverflow.com/questions/45849831/object-entries-alternative-for-internet-explorer-and-reactjs

**Comment by Zenoo** [comment]
This was fixed with f9ab10cefe68529f15c469c0aee8120c0ce450c8
Try upgrading to 1.0.11, it should work.

**Comment by TrevorMartz** [comment]
Quickest response ever, thanks!
